# Generated by Django 5.0 on 2024-12-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
